config/routes.rb
Rails.application.routes.draw do

  root to: 'blog/posts#index'
  # /author/posts
  namespace :author do
    resources :posts
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :most_recent, -> { order(id: :desc) }

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    "Published #{created_at.strftime('%-b %-d, %Y')}"
  end

end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to author_past_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html {  redirect_to author_past_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end



      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end

end

app/controllers/author_controller.rb
class AuthorController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController

    def about

    end

    def contact

    end

  end

end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController
  
    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
        @post = Post.friendly.find(params[:id])
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/author/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_field :banner_image_url %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/author/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, author_post_path(post) %></td>
  <td></td>
  <td><%= link_to 'Edit', edit_author_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', author_post_path(post), method: :delete, data:
   { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/author/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/author/posts/index.html.erb
<% provide(:page_title, 'All Post') %>
<% provide(:author, 'active') %>
<div class="row">
  <div class="">
    <%= link_to 'New post', new_author_post_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <br>
  <br>
    <table class="table table-striped">
      <tr>
        <th colspan="4">Title</th>
      </tr>
      <%= render @posts %>
    </table>
</div>

app/views/author/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>
<h1>New Post</h1>


<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/author/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to 'Edit', edit_author_post_path(@post),
   class: 'btn btn-sm btn-warning' %>
   <%= link_to 'Remove', author_post_path(@post), method: :delete, data:
    { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>

app/views/blog/pages/about.html.erb
<h1>About</h1>

app/views/blog/pages/contact.html.erb
<h1>Contact</h1>

app/views/blog/posts/_post.html.erb
<div class="col-sm-6 col-lg-4">
  <div class="card">
    <%= link_to post do %>
    <div class="card-topper" style="background-image: url(<%= post.banner_image_url %>)">
    </div>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <h6 class="published-date"><%= post.display_day_published %></h6>
      <%= link_to post do %>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <% end %>
      <%= link_to 'Read', post, class: 'btn btn-read' %>

    </div>
  </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Post') %>
<% provide(:blog_active, 'active') %>
<div class="row">
  <% @posts.each do |post| %>
    <%= render @posts %>
  <% end%>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>
<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Testblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Testblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="col-sm-6 col-lg-4">
  <div class="card">
    <%= link_to post do %>
    <div class="card-topper" style="background-image: url(<%= post.banner_image_url %>)">
    </div>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post %></h4>
      <h6 class="published-date"><%= post.display_day_published %></h6>
      <%= link_to post do %>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <% end %>
      <%= link_to 'Read', post, class: 'btn btn-read' %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>
<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="collapse navbar-collapse justify-content-end" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'My posts', author_posts_path, class: "nav-link #{yield(:author)}" %>
        </li>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <a class="navbar-brand" href='/'>
    Schwiftology<span class='light'>Church of Rick and Morty</a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
         <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
         <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My posts', author_posts_path, class: "nav-link #{yield(:author)}" %>
      </li>
    </ul>
  </div>
</nav>